### PR TITLE
feat: add support to configure controller jbod mode

### PR DESCRIPTION
**Pull request by dgilbert101**
Needed the ability to disable/enable jbod mode on controllers that support it. Add the simple functionality to disable or enable it.

### CODE REVIEW

**Comment by ralequi** [comment]
Hi @dgilbert101 !

Thanks for your contrib. However, I have a few questions:

- Don't you think true/false would be greater option rather than on/off?
- Why do you think that would be better than a boolean attribute?
- Could you explain your motivations for an str instead of bool type please?

**Comment by dgilbert101** [comment]
I'm not opposed to true/false, although nothing else is true/false. So the current syntax keeps with the existing nature of the interface.

**Comment by ralequi** [comment]
Good point.

I really dislike keeping something binary as text. So, I would accept this as is, and change into true/false in the future as the other API.

Thanks again for your contrib!

**Comment by dgilbert101** [comment]
Sounds good.

**Pull request merged**
